[package]
name = "mistrustfully/ffox"
description = "A simple programming language written in Lua"
authors = ["Christian Fletcher <mistrustfully@gmail.com>"]
license = "MIT"
version = "1.1.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["out/", "default.project.json"]
exclude = [
	"node_modules",
	"src",
	".eslintrc",
	".prettierrc",
	"aftman.toml",
	"package-lock.json",
	"package.json",
	"selene.toml",
	"stylua.toml",
	"tsconfig.json",
]

[dependencies]
